ignoredBuiltDependencies:
  - chromedriver
  - edgedriver
  - geckodriver

onlyBuiltDependencies:
  - '@swc/core'
  - core-js
  - esbuild
  - husky

preferFrozenLockfile: true
shamefullyHoist: true
shellEmulator: true
verifyDepsBeforeRun: install
